# Model v2 Data Quality Audit

Exploratory audit for the Model v2 data flow. This notebook is read-only: it loads raw transaction and identity parquet files, merges them with `train_transaction` as the left table, and profiles numerical, categorical, and ID-like columns before further FeatureEngineeringV2 changes.

No model training, artifact writing, v1 artifact changes, or `/predict` changes are performed here.

## Setup

Paths are resolved relative to the repository root instead of hardcoded local machine paths.

In [1]:
from pathlib import Path
import sys

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 80)
pd.set_option("display.max_rows", 80)


def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / "ml").exists() and (candidate / "lakehouse").exists():
            return candidate
    raise RuntimeError("Could not locate repository root from notebook path.")


PROJECT_ROOT = find_project_root(Path.cwd().resolve())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

TRANSACTION_PATH = PROJECT_ROOT / "lakehouse" / "raw" / "train_transaction.parquet"
IDENTITY_PATH = PROJECT_ROOT / "lakehouse" / "raw" / "train_identity.parquet"

print(f"PROJECT_ROOT: {PROJECT_ROOT}")
print(f"TRANSACTION_PATH: {TRANSACTION_PATH}")
print(f"IDENTITY_PATH: {IDENTITY_PATH}")

PROJECT_ROOT: /mnt/d/my_AI_projects/enterprise-fraud-detection-ml-system
TRANSACTION_PATH: /mnt/d/my_AI_projects/enterprise-fraud-detection-ml-system/lakehouse/raw/train_transaction.parquet
IDENTITY_PATH: /mnt/d/my_AI_projects/enterprise-fraud-detection-ml-system/lakehouse/raw/train_identity.parquet

## Load Raw Data

The transaction dataset is the source of truth for row count, `TransactionDT`, and `isFraud`. Identity data is optional enrichment keyed by `TransactionID`.

In [2]:
train_transaction = pd.read_parquet(TRANSACTION_PATH)
train_identity = pd.read_parquet(IDENTITY_PATH)

print("train_transaction shape:", train_transaction.shape)
print("train_identity shape:", train_identity.shape)

display(train_transaction.head())
display(train_identity.head())

train_transaction shape: (590540, 394)
train_identity shape: (144233, 41)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,dist1,dist2,P_emaildomain,R_emaildomain,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V300,V301,V302,V303,V304,V305,V306,V307,V308,V309,V310,V311,V312,V313,V314,V315,V316,V317,V318,V319,V320,V321,V322,V323,V324,V325,V326,V327,V328,V329,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,credit,315.0,87.0,19.0,NaN,None,None,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,1.0,1.0,14.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,117.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0,87.0,NaN,NaN,gmail.com,None,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0,87.0,287.0,NaN,outlook.com,None,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0,87.0,NaN,NaN,yahoo.com,None,2.0,5.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,1.0,0.0,25.0,1.0,112.0,112.0,0.0,94.0,0.0,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,50.0,1758.0,925.0,0.0,354.0,0.0,135.0,0.0,0.0,0.0,50.0,1404.0,790.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0,87.0,NaN,NaN,gmail.com,None,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,id_10,id_11,id_12,id_13,id_14,id_15,id_16,id_17,id_18,id_19,id_20,id_21,id_22,id_23,id_24,id_25,id_26,id_27,id_28,id_29,id_30,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NotFound,NaN,-480.0,New,NotFound,166.0,NaN,542.0,144.0,NaN,NaN,None,NaN,NaN,NaN,None,New,NotFound,Android 7.0,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,NaN,100.0,NotFound,49.0,-300.0,New,NotFound,166.0,NaN,621.0,500.0,NaN,NaN,None,NaN,NaN,NaN,None,New,NotFound,iOS 11.1.2,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,100.0,NotFound,52.0,NaN,Found,Found,121.0,NaN,410.0,142.0,NaN,NaN,None,NaN,NaN,NaN,None,Found,Found,None,chrome 62.0,NaN,None,None,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,NaN,100.0,NotFound,52.0,NaN,New,NotFound,225.0,NaN,176.0,507.0,NaN,NaN,None,NaN,NaN,NaN,None,New,NotFound,None,chrome 62.0,NaN,None,None,F,F,T,T,desktop,None
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,0.0,100.0,NotFound,NaN,-300.0,Found,Found,166.0,15.0,529.0,575.0,NaN,NaN,None,NaN,NaN,NaN,None,Found,Found,Mac OS X 10_11_6,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

## Merge Transaction and Identity Data

Use the Model v2 strategy: keep all transaction rows and enrich available identity rows with a left join.

In [3]:
required_transaction_cols = {"TransactionID", "TransactionDT", "isFraud"}
required_identity_cols = {"TransactionID"}

missing_transaction = required_transaction_cols - set(train_transaction.columns)
missing_identity = required_identity_cols - set(train_identity.columns)

if missing_transaction:
    raise ValueError(f"Missing transaction columns: {sorted(missing_transaction)}")
if missing_identity:
    raise ValueError(f"Missing identity columns: {sorted(missing_identity)}")
if "isFraud" in train_identity.columns:
    raise ValueError("train_identity should not contain isFraud.")

merged = train_transaction.merge(train_identity, on="TransactionID", how="left")

print("merged shape:", merged.shape)
print("transaction rows preserved:", len(merged) == len(train_transaction))
print("identity columns added:", len(set(train_identity.columns) - {"TransactionID"}))
display(merged.head())

merged shape: (590540, 434)
transaction rows preserved: True
identity columns added: 40

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,dist1,dist2,P_emaildomain,R_emaildomain,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,id_10,id_11,id_12,id_13,id_14,id_15,id_16,id_17,id_18,id_19,id_20,id_21,id_22,id_23,id_24,id_25,id_26,id_27,id_28,id_29,id_30,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,credit,315.0,87.0,19.0,NaN,None,None,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,1.0,1.0,14.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0,87.0,NaN,NaN,gmail.com,None,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0,87.0,287.0,NaN,outlook.com,None,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0,87.0,NaN,NaN,yahoo.com,None,2.0,5.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,1.0,0.0,25.0,1.0,112.0,112.0,0.0,94.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0,87.0,NaN,NaN,gmail.com,None,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NotFound,NaN,-480.0,New,NotFound,166.0,NaN,542.0,144.0,NaN,NaN,None,NaN,NaN,NaN,None,New,NotFound,Android 7.0,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

## Column Groups

Identify numerical, categorical/object, and ID-like columns for specialized audit views.

In [12]:
numeric_cols = merged.select_dtypes(include=["number", "bool"]).columns.tolist()
object_cols = merged.select_dtypes(include=["object", "category", "string"]).columns.tolist()

id_like_cols = [
    col for col in merged.columns
    if col == "TransactionID"
    or col.startswith("card")
    or col.startswith("addr")
    or col.startswith("id_")
]

print(f"numeric columns: {len(numeric_cols)}")
print(f"object/category columns: {len(object_cols)}")
print(f"ID-like columns: {len(id_like_cols)}")

display(pd.DataFrame({"id_like_columns": id_like_cols}).head(80))

numeric columns: 403
object/category columns: 31
ID-like columns: 47

   id_like_columns
0    TransactionID
1            card1
2            card2
3            card3
4            card4
5            card5
6            card6
7            addr1
8            addr2
9            id_01
10           id_02
11           id_03
12           id_04
13           id_05
14           id_06
15           id_07
16           id_08
17           id_09
18           id_10
19           id_11
20           id_12
21           id_13
22           id_14
23           id_15
24           id_16
25           id_17
26           id_18
27           id_19
28           id_20
29           id_21
30           id_22
31           id_23
32           id_24
33           id_25
34           id_26
35           id_27
36           id_28
37           id_29
38           id_30
39           id_31
40           id_32
41           id_33
42           id_34
43           id_35
44           id_36
45           id_37
46           id_38

## Numerical Column Audit

This summarizes dtype, missingness, conversion risk, central tendency, suspicious negatives, outliers, and constant or near-constant columns.

In [5]:
def audit_numeric_columns(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    n_rows = len(df)
    for col in df.columns:
        series = df[col]
        numeric = pd.to_numeric(series, errors="coerce")
        non_missing = series.notna().sum()
        coerced_missing = numeric.isna().sum()
        coercion_failures = max(int(coerced_missing - series.isna().sum()), 0)
        missing_count = int(series.isna().sum())
        nunique = int(series.nunique(dropna=True))
        q1 = numeric.quantile(0.25)
        q3 = numeric.quantile(0.75)
        iqr = q3 - q1
        lower = q1 - 3 * iqr if pd.notna(iqr) else np.nan
        upper = q3 + 3 * iqr if pd.notna(iqr) else np.nan
        outlier_count = int(((numeric < lower) | (numeric > upper)).sum()) if pd.notna(iqr) else 0
        top_rate = series.value_counts(dropna=True, normalize=True).iloc[0] if non_missing else np.nan
        rows.append({
            "column": col,
            "dtype": str(series.dtype),
            "missing_count": missing_count,
            "missing_rate": missing_count / n_rows if n_rows else np.nan,
            "coercion_failure_count": coercion_failures,
            "coercion_failure_rate": coercion_failures / non_missing if non_missing else 0.0,
            "min": numeric.min(),
            "max": numeric.max(),
            "mean": numeric.mean(),
            "median": numeric.median(),
            "negative_count": int((numeric < 0).sum()),
            "q01": numeric.quantile(0.01),
            "q99": numeric.quantile(0.99),
            "iqr_outlier_count": outlier_count,
            "unique_count": nunique,
            "top_value_rate": top_rate,
            "constant": nunique <= 1,
            "near_constant": bool(pd.notna(top_rate) and top_rate >= 0.99),
        })
    return pd.DataFrame(rows).sort_values(["missing_rate", "coercion_failure_rate"], ascending=False)


numeric_audit = audit_numeric_columns(merged[numeric_cols])
display(numeric_audit.head(80))

,column,dtype,missing_count,missing_rate,coercion_failure_count,coercion_failure_rate,min,max,mean,median,negative_count,q01,q99,iqr_outlier_count,unique_count,top_value_rate,constant,near_constant
399,id_24,float64,585793,0.991962,0,0.0,11.0,26.000000,12.800927,11.000000,0,11.00,21.000000,0,12,0.593427,False,False
400,id_25,float64,585408,0.991310,0,0.0,100.0,548.000000,329.608924,321.000000,0,113.00,528.000000,501,341,0.485970,False,False
386,id_07,float64,585385,0.991271,0,0.0,-46.0,61.000000,13.285354,14.000000,347,-14.46,39.000000,0,84,0.079340,False,False
387,id_08,float64,585385,0.991271,0,0.0,-100.0,0.000000,-38.600388,-34.000000,4894,-100.00,0.000000,0,94,0.096993,False,False
397,id_21,float64,585381,0.991264,0,0.0,100.0,854.000000,368.269820,252.000000,0,131.00,849.000000,0,490,0.492731,False,False
401,id_26,float64,585377,0.991257,0,0.0,100.0,216.000000,149.070308,149.000000,0,100.00,216.000000,0,95,0.159597,False,False
398,id_22,float64,585371,0.991247,0,0.0,10.0,44.000000,16.002708,14.000000,0,14.00,41.000000,433,25,0.916231,False,False
11,dist2,float64,552913,0.936284,0,0.0,0.0,11623.000000,231.855423,37.000000,0,0.00,2367.480000,2770,1751,0.151141,False,False
32,D7,float64,551623,0.934099,0,0.0,0.0,843.000000,41.638950,0.000000,0,0.00,429.000000,5941,597,0.543079,False,False
394,id_18,float64,545427,0.923607,0,0.0,10.0,29.000000,14.237337,15.000000,0,12.00,20.000000,188,18,0.565003,False,False
38,D13,float64,528588,0.895093,0,0.0,0.0,847.000000,17.901295,0.000000,0,0.00,371.490000,13112,577,0.788352,False,False
39,D14,float64,528353,0.894695,0,0.0,-193.0,878.000000,57.724444,0.000000,3,0.00,562.000000,13970,802,0.727901,False,False
37,D12,float64,525823,0.890410,0,0.0,-83.0,648.000000,54.037533,0.000000,2,0.00,514.000000,12533,635,0.660661,False,False
382,id_03,float64,524216,0.887689,0,0.0,-13.0,10.000000,0.060189,0.000000,187,0.00,3.000000,2421,24,0.963497,False,False
383,id_04,float64,524216,0.887689,0,0.0,-28.0,0.000000,-0.058938,0.000000,585,0.00,0.000000,585,15,0.991180,False,True
31,D6,float64,517353,0.876068,0,0.0,-83.0,873.000000,69.805717,0.000000,3,0.00,593.000000,12665,829,0.625548,False,False
33,D8,float64,515614,0.873123,0,0.0,0.0,1707.791626,146.058108,37.875000,0,0.00,983.927063,3637,12353,0.018031,False,False
34,D9,float64,515614,0.873123,0,0.0,0.0,0.958333,0.561057,0.666666,0,0.00,0.958333,0,24,0.071911,False,False
388,id_09,float64,515614,0.873123,0,0.0,-36.0,25.000000,0.091023,0.000000,463,0.00,3.000000,4548,46,0.939300,False,False
389,id_10,float64,515614,0.873123,0,0.0,-100.0,0.000000,-0.301124,0.000000,2047,-10.00,0.000000,2047,62,0.972680,False,False
402,id_32,float64,512954,0.868619,0,0.0,0.0,32.000000,26.508597,24.000000,0,24.00,32.000000,0,4,0.684028,False,False
392,id_14,float64,510496,0.864456,0,0.0,-660.0,720.000000,-344.507146,-300.000000,79113,-480.00,0.000000,1431,25,0.551209,False,False
178,V138,float64,508595,0.861237,0,0.0,0.0,22.000000,0.036439,0.000000,0,0.00,1.000000,1335,23,0.983709,False,False
179,V139,float64,508595,0.861237,0,0.0,0.0,33.000000,1.073915,1.000000,0,0.00,6.000000,1897,34,0.578803,False,False
180,V140,float64,508595,0.861237,0,0.0,0.0,33.000000,1.125267,1.000000,0,0.00,7.000000,2372,34,0.568650,False,False
181,V141,float64,508595,0.861237,0,0.0,0.0,5.000000,0.037696,0.000000,0,0.00,1.000000,2734,6,0.966636,False,False
182,V142,float64,508595,0.861237,0,0.0,0.0,9.000000,0.048581,0.000000,0,0.00,1.000000,2793,10,0.965916,False,False
186,V146,float64,508595,0.861237,0,0.0,0.0,24.000000,0.156276,0.000000,0,0.00,3.000000,7227,25,0.911807,False,False
187,V147,float64,508595,0.861237,0,0.0,0.0,26.000000,0.168601,0.000000,0,0.00,3.000000,7414,27,0.909525,False,False
188,V148,float64,508595,0.861237,0,0.0,0.0,20.000000,0.765001,1.000000,0,0.00,2.000000,110,21,0.715724,False,False
189,V149,float64,508595,0.861237,0,0.0,0.0,20.000000,0.775313,1.000000,0,0.00,2.000000,181,21,0.712307,False,False
193,V153,float64,508595,0.861237,0,0.0,0.0,18.000000,0.753200,1.000000,0,0.00,2.000000,60,19,0.721740,False,False
194,V154,float64,508595,0.861237,0,0.0,0.0,18.000000,0.757423,1.000000,0,0.00,2.000000,86,19,0.720398,False,False
195,V155,float64,508595,0.861237,0,0.0,0.0,24.000000,0.767381,1.000000,0,0.00,2.000000,121,25,0.714919,False,False
196,V156,float64,508595,0.861237,0,0.0,0.0,24.000000,0.777485,1.000000,0,0.00,2.000000,194,25,0.711477,False,False
197,V157,float64,508595,0.861237,0,0.0,0.0,24.000000,0.817573,1.000000,0,0.00,3.000000,179,25,0.674599,False,False
198,V158,float64,508595,0.861237,0,0.0,0.0,24.000000,0.833461,1.000000,0,0.00,3.000000,277,25,0.668058,False,False
201,V161,float64,508595,0.861237,0,0.0,0.0,3300.000000,4.843938,0.000000,0,0.00,100.000000,2734,79,0.966636,False,False
202,V162,float64,508595,0.861237,0,0.0,0.0,3300.000000,6.594661,0.000000,0,0.00,168.000000,2937,185,0.964159,False,False
203,V163,float64,508595,0.861237,0,0.0,0.0,3300.000000,5.505955,0.000000,0,0.00,150.000000,2793,106,0.965916,False,False
183,V143,float64,508589,0.861227,0,0.0,0.0,869.000000,8.397006,0.000000,0,0.00,219.000000,18079,870,0.779393,False,False
184,V144,float64,508589,0.861227,0,0.0,0.0,62.000000,3.708484,0.000000,0,0.00,47.000000,19512,63,0.761907,False,False
185,V145,float64,508589,0.861227,0,0.0,0.0,297.000000,22.112946,0.000000,0,0.00,285.000000,12706,260,0.747288,False,False
190,V150,float64,508589,0.861227,0,0.0,1.0,3389.000000,277.598028,1.000000,0,1.00,3339.000000,14392,1996,0.824383,False,False
191,V151,float64,508589,0.861227,0,0.0,1.0,57.000000,6.460190,1.000000,0,1.00,55.000000,11853,56,0.855365,False,False
192,V152,float64,508589,0.861227,0,0.0,1.0,69.000000,9.432710,1.000000,0,1.00,68.000000,13887,39,0.830545,False,False
199,V159,float64,508589,0.861227,0,0.0,0.0,55125.000000,2719.299775,0.000000,0,0.00,37350.480469,13554,6663,0.834608,False,False
200,V160,float64,508589,0.861227,0,0.0,0.0,641511.437500,47453.181173,0.000000,0,0.00,623983.437500,18610,9621,0.772913,False,False
204,V164,float64,508589,0.861227,0,0.0,0.0,93736.000000,877.888928,0.000000,0,0.00,23075.500000,18079,1978,0.779393,False,False
205,V165,float64,508589,0.861227,0,0.0,0.0,98476.000000,2239.912219,0.000000,0,0.00,42118.000000,19353,2547,0.763847,False,False
206,V166,float64,508589,0.861227,0,0.0,0.0,104060.000000,359.469437,0.000000,0,0.00,4523.979980,19512,987,0.761907,False,False
362,V322,float64,508189,0.860550,0,0.0,0.0,880.000000,6.220289,0.000000,0,0.00,231.000000,16381,881,0.801083,False,False
363,V323,float64,508189,0.860550,0,0.0,0.0,1411.000000,13.103775,0.000000,0,0.00,594.500000,5019,1411,0.738376,False,False
364,V324,float64,508189,0.860550,0,0.0,0.0,976.000000,9.184612,0.000000,0,0.00,457.000000,19406,976,0.764350,False,False
365,V325,float64,508189,0.860550,0,0.0,0.0,12.000000,0.058494,0.000000,0,0.00,1.000000,3763,13,0.954305,False,False
366,V326,float64,508189,0.860550,0,0.0,0.0,44.000000,0.851040,0.000000,0,0.00,27.000000,9683,45,0.882418,False,False
367,V327,float64,508189,0.860550,0,0.0,0.0,18.000000,0.296633,0.000000,0,0.00,9.000000,7253,19,0.911926,False,False
368,V328,float64,508189,0.860550,0,0.0,0.0,15.000000,0.336790,0.000000,0,0.00,11.000000,8887,16,0.892084,False,False
369,V329,float64,508189,0.860550,0,0.0,0.0,99.000000,1.312844,0.000000,0,0.00,77.000000,10237,100,0.875691,False,False
370,V330,float64,508189,0.860550,0,0.0,0.0,55.000000,0.775874,0.000000,0,0.00,35.000000,9552,56,0.884009,False,False
371,V331,float64,508189,0.860550,0,0.0,0.0,160000.000000,721.741883,0.000000,0,0.00,24842.500000,16381,1758,0.801083,False,False
372,V332,float64,508189,0.860550,0,0.0,0.0,160000.000000,1375.783644,0.000000,0,0.00,60335.000000,13537,2453,0.738376,False,False
373,V333,float64,508189,0.860550,0,0.0,0.0,160000.000000,1014.622782,0.000000,0,0.00,47654.000000,19406,1971,0.764350,False,False
374,V334,float64,508189,0.860550,0,0.0,0.0,55125.000000,9.807015,0.000000,0,0.00,200.000000,3763,143,0.954305,False,False
375,V335,float64,508189,0.860550,0,0.0,0.0,55125.000000,59.164550,0.000000,0,0.00,2301.000000,9683,672,0.882418,False,False
376,V336,float64,508189,0.860550,0,0.0,0.0,55125.000000,28.530903,0.000000,0,0.00,1000.000000,7253,356,0.911926,False,False
377,V337,float64,508189,0.860550,0,0.0,0.0,104060.000000,55.352422,0.000000,0,0.00,1165.000000,8887,254,0.892084,False,False
378,V338,float64,508189,0.860550,0,0.0,0.0,104060.000000,151.160542,0.000000,0,0.00,7709.000000,10237,380,0.875691,False,False
379,V339,float64,508189,0.860550,0,0.0,0.0,104060.000000,100.700882,0.000000,0,0.00,3657.000000,9552,334,0.884009,False,False
391,id_13,float64,463220,0.784401,0,0.0,10.0,64.000000,48.053071,52.000000,0,14.00,64.000000,40299,54,0.456323,False,False
257,V217,float64,460110,0.779134,0,0.0,0.0,303.000000,1.054619,0.000000,0,0.00,10.000000,32145,304,0.753546,False,False
258,V218,float64,460110,0.779134,0,0.0,0.0,400.000000,1.725784,0.000000,0,0.00,17.000000,7599,401,0.692586,False,False
259,V219,float64,460110,0.779134,0,0.0,0.0,378.000000,1.367132,0.000000,0,0.00,13.000000,5756,379,0.723277,False,False
263,V223,float64,460110,0.779134,0,0.0,0.0,16.000000,0.093153,0.000000,0,0.00,2.000000,9915,17,0.923982,False,False
264,V224,float64,460110,0.779134,0,0.0,0.0,144.000000,0.394748,0.000000,0,0.00,6.000000,18377,79,0.859105,False,False
265,V225,float64,460110,0.779134,0,0.0,0.0,51.000000,0.191758,0.000000,0,0.00,3.000000,14107,35,0.891842,False,False
266,V226,float64,460110,0.779134,0,0.0,0.0,242.000000,0.247612,0.000000,0,0.00,4.000000,8059,81,0.938212,False,False
268,V228,float64,460110,0.779134,0,0.0,0.0,54.000000,1.351928,1.000000,0,1.00,7.000000,19364,55,0.851537,False,False
269,V229,float64,460110,0.779134,0,0.0,0.0,176.000000,1.638710,1.000000,0,1.00,10.000000,26423,91,0.797416,False,False
270,V230,float64,460110,0.779134,0,0.0,0.0,65.000000,1.465476,1.000000,0,1.00,8.000000,22581,66,0.826873,False,False

In [6]:
print("Columns with suspicious negative values:")
display(numeric_audit[numeric_audit["negative_count"] > 0].head(50))

print("Constant or near-constant numerical columns:")
display(numeric_audit[numeric_audit["constant"] | numeric_audit["near_constant"]].head(80))

print("High missing numerical columns:")
display(numeric_audit[numeric_audit["missing_rate"] >= 0.5].head(80))

Columns with suspicious negative values:

,column,dtype,missing_count,missing_rate,coercion_failure_count,coercion_failure_rate,min,max,mean,median,negative_count,q01,q99,iqr_outlier_count,unique_count,top_value_rate,constant,near_constant
386,id_07,float64,585385,0.991271,0,0.0,-46.0,61.0,13.285354,14.0,347,-14.46,39.0,0,84,0.079340,False,False
387,id_08,float64,585385,0.991271,0,0.0,-100.0,0.0,-38.600388,-34.0,4894,-100.00,0.0,0,94,0.096993,False,False
39,D14,float64,528353,0.894695,0,0.0,-193.0,878.0,57.724444,0.0,3,0.00,562.0,13970,802,0.727901,False,False
37,D12,float64,525823,0.890410,0,0.0,-83.0,648.0,54.037533,0.0,2,0.00,514.0,12533,635,0.660661,False,False
382,id_03,float64,524216,0.887689,0,0.0,-13.0,10.0,0.060189,0.0,187,0.00,3.0,2421,24,0.963497,False,False
383,id_04,float64,524216,0.887689,0,0.0,-28.0,0.0,-0.058938,0.0,585,0.00,0.0,585,15,0.991180,False,True
31,D6,float64,517353,0.876068,0,0.0,-83.0,873.0,69.805717,0.0,3,0.00,593.0,12665,829,0.625548,False,False
388,id_09,float64,515614,0.873123,0,0.0,-36.0,25.0,0.091023,0.0,463,0.00,3.0,4548,46,0.939300,False,False
389,id_10,float64,515614,0.873123,0,0.0,-100.0,0.0,-0.301124,0.0,2047,-10.00,0.0,2047,62,0.972680,False,False
392,id_14,float64,510496,0.864456,0,0.0,-660.0,720.0,-344.507146,-300.0,79113,-480.00,0.0,1431,25,0.551209,False,False
384,id_05,float64,453675,0.768238,0,0.0,-72.0,52.0,1.615585,0.0,6097,-9.00,25.0,22245,93,0.677624,False,False
385,id_06,float64,453675,0.768238,0,0.0,-100.0,0.0,-6.698710,0.0,45540,-100.00,0.0,13422,101,0.667263,False,False
380,id_01,float64,446307,0.755761,0,0.0,-100.0,0.0,-10.170502,-5.0,124678,-95.00,0.0,9591,77,0.569703,False,False
36,D11,float64,279287,0.472935,0,0.0,-53.0,670.0,146.621465,43.0,7,0.00,609.0,0,676,0.360739,False,False
29,D4,float64,168922,0.286047,0,0.0,-122.0,869.0,140.002441,26.0,15,0.00,623.0,0,808,0.395076,False,False
40,D15,float64,89113,0.150901,0,0.0,-83.0,879.0,163.744579,52.0,15,0.00,635.0,0,859,0.347500,False,False

Constant or near-constant numerical columns:

,column,dtype,missing_count,missing_rate,coercion_failure_count,coercion_failure_rate,min,max,mean,median,negative_count,q01,q99,iqr_outlier_count,unique_count,top_value_rate,constant,near_constant
383,id_04,float64,524216,0.887689,0,0.0,-28.0,0.0,-0.058938,0.0,585,0.0,0.0,585,15,0.991180,False,True
280,V240,float64,460110,0.779134,0,0.0,0.0,7.0,1.000997,1.0,0,1.0,1.0,100,6,0.999233,False,True
281,V241,float64,460110,0.779134,0,0.0,0.0,5.0,1.000238,1.0,0,1.0,1.0,36,5,0.999724,False,True
41,V1,float64,279287,0.472935,0,0.0,0.0,1.0,0.999945,1.0,0,1.0,1.0,17,2,0.999945,False,True
81,V41,float64,168969,0.286126,0,0.0,0.0,1.0,0.999269,1.0,0,1.0,1.0,308,2,0.999269,False,True
128,V88,float64,89164,0.150987,0,0.0,0.0,1.0,0.999246,1.0,0,1.0,1.0,378,2,0.999246,False,True
129,V89,float64,89164,0.150987,0,0.0,0.0,2.0,0.000902,0.0,0,0.0,0.0,422,3,0.999158,False,True
105,V65,float64,77096,0.130552,0,0.0,0.0,1.0,0.999663,1.0,0,1.0,1.0,173,2,0.999663,False,True
108,V68,float64,77096,0.130552,0,0.0,0.0,2.0,0.000534,0.0,0,0.0,0.0,266,3,0.999482,False,True
54,V14,float64,76073,0.128819,0,0.0,0.0,1.0,0.999500,1.0,0,1.0,1.0,257,2,0.999500,False,True
67,V27,float64,76073,0.128819,0,0.0,0.0,4.0,0.000776,0.0,0,0.0,0.0,391,4,0.999240,False,True
68,V28,float64,76073,0.128819,0,0.0,0.0,4.0,0.000830,0.0,0,0.0,0.0,394,4,0.999234,False,True
9,addr2,float64,65706,0.111264,0,0.0,10.0,102.0,86.800630,87.0,0,87.0,87.0,4353,74,0.991706,False,True
147,V107,float64,314,0.000532,0,0.0,0.0,1.0,0.999580,1.0,0,1.0,1.0,248,2,0.999580,False,True
148,V108,float64,314,0.000532,0,0.0,0.0,7.0,1.004613,1.0,0,1.0,1.0,2984,8,0.994944,False,True
150,V110,float64,314,0.000532,0,0.0,0.0,7.0,1.007739,1.0,0,1.0,1.0,4665,8,0.992096,False,True
151,V111,float64,314,0.000532,0,0.0,0.0,9.0,1.002563,1.0,0,1.0,1.0,1727,10,0.997074,False,True
152,V112,float64,314,0.000532,0,0.0,0.0,9.0,1.005356,1.0,0,1.0,1.0,2993,10,0.994929,False,True
153,V113,float64,314,0.000532,0,0.0,0.0,9.0,1.003383,1.0,0,1.0,1.0,2058,10,0.996513,False,True
154,V114,float64,314,0.000532,0,0.0,0.0,6.0,1.009298,1.0,0,1.0,1.0,5538,7,0.990617,False,True
157,V117,float64,314,0.000532,0,0.0,0.0,3.0,1.000391,1.0,0,1.0,1.0,727,4,0.998768,False,True
158,V118,float64,314,0.000532,0,0.0,0.0,3.0,1.001474,1.0,0,1.0,1.0,988,4,0.998326,False,True
159,V119,float64,314,0.000532,0,0.0,0.0,3.0,1.000729,1.0,0,1.0,1.0,776,4,0.998685,False,True
160,V120,float64,314,0.000532,0,0.0,0.0,3.0,1.000874,1.0,0,1.0,1.0,1008,4,0.998292,False,True
161,V121,float64,314,0.000532,0,0.0,0.0,3.0,1.004276,1.0,0,1.0,1.0,2632,4,0.995541,False,True
162,V122,float64,314,0.000532,0,0.0,0.0,3.0,1.001759,1.0,0,1.0,1.0,1380,4,0.997662,False,True
345,V305,float64,12,0.000020,0,0.0,1.0,2.0,1.000007,1.0,0,1.0,1.0,4,2,0.999993,False,True
14,C3,float64,0,0.000000,0,0.0,0.0,26.0,0.005644,0.0,0,0.0,0.0,2429,27,0.995887,False,True

High missing numerical columns:

,column,dtype,missing_count,missing_rate,coercion_failure_count,coercion_failure_rate,min,max,mean,median,negative_count,q01,q99,iqr_outlier_count,unique_count,top_value_rate,constant,near_constant
399,id_24,float64,585793,0.991962,0,0.0,11.0,26.000000,12.800927,11.000000,0,11.00,21.000000,0,12,0.593427,False,False
400,id_25,float64,585408,0.991310,0,0.0,100.0,548.000000,329.608924,321.000000,0,113.00,528.000000,501,341,0.485970,False,False
386,id_07,float64,585385,0.991271,0,0.0,-46.0,61.000000,13.285354,14.000000,347,-14.46,39.000000,0,84,0.079340,False,False
387,id_08,float64,585385,0.991271,0,0.0,-100.0,0.000000,-38.600388,-34.000000,4894,-100.00,0.000000,0,94,0.096993,False,False
397,id_21,float64,585381,0.991264,0,0.0,100.0,854.000000,368.269820,252.000000,0,131.00,849.000000,0,490,0.492731,False,False
401,id_26,float64,585377,0.991257,0,0.0,100.0,216.000000,149.070308,149.000000,0,100.00,216.000000,0,95,0.159597,False,False
398,id_22,float64,585371,0.991247,0,0.0,10.0,44.000000,16.002708,14.000000,0,14.00,41.000000,433,25,0.916231,False,False
11,dist2,float64,552913,0.936284,0,0.0,0.0,11623.000000,231.855423,37.000000,0,0.00,2367.480000,2770,1751,0.151141,False,False
32,D7,float64,551623,0.934099,0,0.0,0.0,843.000000,41.638950,0.000000,0,0.00,429.000000,5941,597,0.543079,False,False
394,id_18,float64,545427,0.923607,0,0.0,10.0,29.000000,14.237337,15.000000,0,12.00,20.000000,188,18,0.565003,False,False
38,D13,float64,528588,0.895093,0,0.0,0.0,847.000000,17.901295,0.000000,0,0.00,371.490000,13112,577,0.788352,False,False
39,D14,float64,528353,0.894695,0,0.0,-193.0,878.000000,57.724444,0.000000,3,0.00,562.000000,13970,802,0.727901,False,False
37,D12,float64,525823,0.890410,0,0.0,-83.0,648.000000,54.037533,0.000000,2,0.00,514.000000,12533,635,0.660661,False,False
382,id_03,float64,524216,0.887689,0,0.0,-13.0,10.000000,0.060189,0.000000,187,0.00,3.000000,2421,24,0.963497,False,False
383,id_04,float64,524216,0.887689,0,0.0,-28.0,0.000000,-0.058938,0.000000,585,0.00,0.000000,585,15,0.991180,False,True
31,D6,float64,517353,0.876068,0,0.0,-83.0,873.000000,69.805717,0.000000,3,0.00,593.000000,12665,829,0.625548,False,False
33,D8,float64,515614,0.873123,0,0.0,0.0,1707.791626,146.058108,37.875000,0,0.00,983.927063,3637,12353,0.018031,False,False
34,D9,float64,515614,0.873123,0,0.0,0.0,0.958333,0.561057,0.666666,0,0.00,0.958333,0,24,0.071911,False,False
388,id_09,float64,515614,0.873123,0,0.0,-36.0,25.000000,0.091023,0.000000,463,0.00,3.000000,4548,46,0.939300,False,False
389,id_10,float64,515614,0.873123,0,0.0,-100.0,0.000000,-0.301124,0.000000,2047,-10.00,0.000000,2047,62,0.972680,False,False
402,id_32,float64,512954,0.868619,0,0.0,0.0,32.000000,26.508597,24.000000,0,24.00,32.000000,0,4,0.684028,False,False
392,id_14,float64,510496,0.864456,0,0.0,-660.0,720.000000,-344.507146,-300.000000,79113,-480.00,0.000000,1431,25,0.551209,False,False
178,V138,float64,508595,0.861237,0,0.0,0.0,22.000000,0.036439,0.000000,0,0.00,1.000000,1335,23,0.983709,False,False
179,V139,float64,508595,0.861237,0,0.0,0.0,33.000000,1.073915,1.000000,0,0.00,6.000000,1897,34,0.578803,False,False
180,V140,float64,508595,0.861237,0,0.0,0.0,33.000000,1.125267,1.000000,0,0.00,7.000000,2372,34,0.568650,False,False
181,V141,float64,508595,0.861237,0,0.0,0.0,5.000000,0.037696,0.000000,0,0.00,1.000000,2734,6,0.966636,False,False
182,V142,float64,508595,0.861237,0,0.0,0.0,9.000000,0.048581,0.000000,0,0.00,1.000000,2793,10,0.965916,False,False
186,V146,float64,508595,0.861237,0,0.0,0.0,24.000000,0.156276,0.000000,0,0.00,3.000000,7227,25,0.911807,False,False
187,V147,float64,508595,0.861237,0,0.0,0.0,26.000000,0.168601,0.000000,0,0.00,3.000000,7414,27,0.909525,False,False
188,V148,float64,508595,0.861237,0,0.0,0.0,20.000000,0.765001,1.000000,0,0.00,2.000000,110,21,0.715724,False,False
189,V149,float64,508595,0.861237,0,0.0,0.0,20.000000,0.775313,1.000000,0,0.00,2.000000,181,21,0.712307,False,False
193,V153,float64,508595,0.861237,0,0.0,0.0,18.000000,0.753200,1.000000,0,0.00,2.000000,60,19,0.721740,False,False
194,V154,float64,508595,0.861237,0,0.0,0.0,18.000000,0.757423,1.000000,0,0.00,2.000000,86,19,0.720398,False,False
195,V155,float64,508595,0.861237,0,0.0,0.0,24.000000,0.767381,1.000000,0,0.00,2.000000,121,25,0.714919,False,False
196,V156,float64,508595,0.861237,0,0.0,0.0,24.000000,0.777485,1.000000,0,0.00,2.000000,194,25,0.711477,False,False
197,V157,float64,508595,0.861237,0,0.0,0.0,24.000000,0.817573,1.000000,0,0.00,3.000000,179,25,0.674599,False,False
198,V158,float64,508595,0.861237,0,0.0,0.0,24.000000,0.833461,1.000000,0,0.00,3.000000,277,25,0.668058,False,False
201,V161,float64,508595,0.861237,0,0.0,0.0,3300.000000,4.843938,0.000000,0,0.00,100.000000,2734,79,0.966636,False,False
202,V162,float64,508595,0.861237,0,0.0,0.0,3300.000000,6.594661,0.000000,0,0.00,168.000000,2937,185,0.964159,False,False
203,V163,float64,508595,0.861237,0,0.0,0.0,3300.000000,5.505955,0.000000,0,0.00,150.000000,2793,106,0.965916,False,False
183,V143,float64,508589,0.861227,0,0.0,0.0,869.000000,8.397006,0.000000,0,0.00,219.000000,18079,870,0.779393,False,False
184,V144,float64,508589,0.861227,0,0.0,0.0,62.000000,3.708484,0.000000,0,0.00,47.000000,19512,63,0.761907,False,False
185,V145,float64,508589,0.861227,0,0.0,0.0,297.000000,22.112946,0.000000,0,0.00,285.000000,12706,260,0.747288,False,False
190,V150,float64,508589,0.861227,0,0.0,1.0,3389.000000,277.598028,1.000000,0,1.00,3339.000000,14392,1996,0.824383,False,False
191,V151,float64,508589,0.861227,0,0.0,1.0,57.000000,6.460190,1.000000,0,1.00,55.000000,11853,56,0.855365,False,False
192,V152,float64,508589,0.861227,0,0.0,1.0,69.000000,9.432710,1.000000,0,1.00,68.000000,13887,39,0.830545,False,False
199,V159,float64,508589,0.861227,0,0.0,0.0,55125.000000,2719.299775,0.000000,0,0.00,37350.480469,13554,6663,0.834608,False,False
200,V160,float64,508589,0.861227,0,0.0,0.0,641511.437500,47453.181173,0.000000,0,0.00,623983.437500,18610,9621,0.772913,False,False
204,V164,float64,508589,0.861227,0,0.0,0.0,93736.000000,877.888928,0.000000,0,0.00,23075.500000,18079,1978,0.779393,False,False
205,V165,float64,508589,0.861227,0,0.0,0.0,98476.000000,2239.912219,0.000000,0,0.00,42118.000000,19353,2547,0.763847,False,False
206,V166,float64,508589,0.861227,0,0.0,0.0,104060.000000,359.469437,0.000000,0,0.00,4523.979980,19512,987,0.761907,False,False
362,V322,float64,508189,0.860550,0,0.0,0.0,880.000000,6.220289,0.000000,0,0.00,231.000000,16381,881,0.801083,False,False
363,V323,float64,508189,0.860550,0,0.0,0.0,1411.000000,13.103775,0.000000,0,0.00,594.500000,5019,1411,0.738376,False,False
364,V324,float64,508189,0.860550,0,0.0,0.0,976.000000,9.184612,0.000000,0,0.00,457.000000,19406,976,0.764350,False,False
365,V325,float64,508189,0.860550,0,0.0,0.0,12.000000,0.058494,0.000000,0,0.00,1.000000,3763,13,0.954305,False,False
366,V326,float64,508189,0.860550,0,0.0,0.0,44.000000,0.851040,0.000000,0,0.00,27.000000,9683,45,0.882418,False,False
367,V327,float64,508189,0.860550,0,0.0,0.0,18.000000,0.296633,0.000000,0,0.00,9.000000,7253,19,0.911926,False,False
368,V328,float64,508189,0.860550,0,0.0,0.0,15.000000,0.336790,0.000000,0,0.00,11.000000,8887,16,0.892084,False,False
369,V329,float64,508189,0.860550,0,0.0,0.0,99.000000,1.312844,0.000000,0,0.00,77.000000,10237,100,0.875691,False,False
370,V330,float64,508189,0.860550,0,0.0,0.0,55.000000,0.775874,0.000000,0,0.00,35.000000,9552,56,0.884009,False,False
371,V331,float64,508189,0.860550,0,0.0,0.0,160000.000000,721.741883,0.000000,0,0.00,24842.500000,16381,1758,0.801083,False,False
372,V332,float64,508189,0.860550,0,0.0,0.0,160000.000000,1375.783644,0.000000,0,0.00,60335.000000,13537,2453,0.738376,False,False
373,V333,float64,508189,0.860550,0,0.0,0.0,160000.000000,1014.622782,0.000000,0,0.00,47654.000000,19406,1971,0.764350,False,False
374,V334,float64,508189,0.860550,0,0.0,0.0,55125.000000,9.807015,0.000000,0,0.00,200.000000,3763,143,0.954305,False,False
375,V335,float64,508189,0.860550,0,0.0,0.0,55125.000000,59.164550,0.000000,0,0.00,2301.000000,9683,672,0.882418,False,False
376,V336,float64,508189,0.860550,0,0.0,0.0,55125.000000,28.530903,0.000000,0,0.00,1000.000000,7253,356,0.911926,False,False
377,V337,float64,508189,0.860550,0,0.0,0.0,104060.000000,55.352422,0.000000,0,0.00,1165.000000,8887,254,0.892084,False,False
378,V338,float64,508189,0.860550,0,0.0,0.0,104060.000000,151.160542,0.000000,0,0.00,7709.000000,10237,380,0.875691,False,False
379,V339,float64,508189,0.860550,0,0.0,0.0,104060.000000,100.700882,0.000000,0,0.00,3657.000000,9552,334,0.884009,False,False
391,id_13,float64,463220,0.784401,0,0.0,10.0,64.000000,48.053071,52.000000,0,14.00,64.000000,40299,54,0.456323,False,False
257,V217,float64,460110,0.779134,0,0.0,0.0,303.000000,1.054619,0.000000,0,0.00,10.000000,32145,304,0.753546,False,False
258,V218,float64,460110,0.779134,0,0.0,0.0,400.000000,1.725784,0.000000,0,0.00,17.000000,7599,401,0.692586,False,False
259,V219,float64,460110,0.779134,0,0.0,0.0,378.000000,1.367132,0.000000,0,0.00,13.000000,5756,379,0.723277,False,False
263,V223,float64,460110,0.779134,0,0.0,0.0,16.000000,0.093153,0.000000,0,0.00,2.000000,9915,17,0.923982,False,False
264,V224,float64,460110,0.779134,0,0.0,0.0,144.000000,0.394748,0.000000,0,0.00,6.000000,18377,79,0.859105,False,False
265,V225,float64,460110,0.779134,0,0.0,0.0,51.000000,0.191758,0.000000,0,0.00,3.000000,14107,35,0.891842,False,False
266,V226,float64,460110,0.779134,0,0.0,0.0,242.000000,0.247612,0.000000,0,0.00,4.000000,8059,81,0.938212,False,False
268,V228,float64,460110,0.779134,0,0.0,0.0,54.000000,1.351928,1.000000,0,1.00,7.000000,19364,55,0.851537,False,False
269,V229,float64,460110,0.779134,0,0.0,0.0,176.000000,1.638710,1.000000,0,1.00,10.000000,26423,91,0.797416,False,False
270,V230,float64,460110,0.779134,0,0.0,0.0,65.000000,1.465476,1.000000,0,1.00,8.000000,22581,66,0.826873,False,False

## Categorical/Object Column Audit

This profiles cardinality, missingness, common values, high-cardinality fields, and mixed Python value types.

In [7]:
def audit_categorical_columns(df: pd.DataFrame, top_n: int = 5) -> pd.DataFrame:
    rows = []
    n_rows = len(df)
    for col in df.columns:
        series = df[col]
        missing_count = int(series.isna().sum())
        value_counts = series.value_counts(dropna=True).head(top_n)
        type_counts = series.dropna().map(lambda x: type(x).__name__).value_counts().head(5)
        rows.append({
            "column": col,
            "dtype": str(series.dtype),
            "unique_count": int(series.nunique(dropna=True)),
            "missing_count": missing_count,
            "missing_rate": missing_count / n_rows if n_rows else np.nan,
            "top_values": value_counts.to_dict(),
            "high_cardinality": series.nunique(dropna=True) > max(100, 0.05 * n_rows),
            "observed_python_types": type_counts.to_dict(),
            "mixed_type_examples": len(type_counts) > 1,
        })
    return pd.DataFrame(rows).sort_values(["high_cardinality", "missing_rate", "unique_count"], ascending=False)


categorical_audit = audit_categorical_columns(merged[object_cols])
display(categorical_audit.head(80))

,column,dtype,unique_count,missing_count,missing_rate,top_values,high_cardinality,observed_python_types,mixed_type_examples
17,id_23,object,3,585371,0.991247,"{'IP_PROXY:TRANSPARENT': 3489, 'IP_PROXY:ANONY...",False,{'str': 5169},False
18,id_27,object,2,585371,0.991247,"{'Found': 5155, 'NotFound': 14}",False,{'str': 5169},False
23,id_33,object,260,517251,0.875895,"{'1920x1080': 16874, '1366x768': 8605, '1334x7...",False,{'str': 73289},False
21,id_30,object,75,512975,0.868654,"{'Windows 10': 21155, 'Windows 7': 13110, 'iOS...",False,{'str': 77565},False
24,id_34,object,4,512735,0.868248,"{'match_status:2': 60011, 'match_status:1': 17...",False,{'str': 77805},False
30,DeviceInfo,object,1786,471874,0.799055,"{'Windows': 47722, 'iOS Device': 19782, 'MacOS...",False,{'str': 118666},False
16,id_16,object,2,461200,0.780980,"{'Found': 66324, 'NotFound': 63016}",False,{'str': 129340},False
4,R_emaildomain,object,60,453249,0.767516,"{'gmail.com': 57147, 'hotmail.com': 27509, 'an...",False,{'str': 137291},False
22,id_31,object,130,450258,0.762451,"{'chrome 63.0': 22000, 'mobile safari 11.0': 1...",False,{'str': 140282},False
29,DeviceType,object,2,449730,0.761557,"{'desktop': 85165, 'mobile': 55645}",False,{'str': 140810},False
19,id_28,object,2,449562,0.761273,"{'Found': 76232, 'New': 64746}",False,{'str': 140978},False
20,id_29,object,2,449562,0.761273,"{'Found': 74926, 'NotFound': 66052}",False,{'str': 140978},False
15,id_15,object,3,449555,0.761261,"{'Found': 67728, 'New': 61612, 'Unknown': 11645}",False,{'str': 140985},False
25,id_35,object,2,449555,0.761261,"{'T': 77814, 'F': 63171}",False,{'str': 140985},False
26,id_36,object,2,449555,0.761261,"{'F': 134066, 'T': 6919}",False,{'str': 140985},False
27,id_37,object,2,449555,0.761261,"{'T': 110452, 'F': 30533}",False,{'str': 140985},False
28,id_38,object,2,449555,0.761261,"{'F': 73922, 'T': 67063}",False,{'str': 140985},False
14,id_12,object,2,446307,0.755761,"{'NotFound': 123025, 'Found': 21208}",False,{'str': 144233},False
9,M5,object,2,350482,0.593494,"{'F': 132491, 'T': 107567}",False,{'str': 240058},False
11,M7,object,2,346265,0.586353,"{'F': 211374, 'T': 32901}",False,{'str': 244275},False
12,M8,object,2,346252,0.586331,"{'F': 155251, 'T': 89037}",False,{'str': 244288},False
13,M9,object,2,346252,0.586331,"{'T': 205656, 'F': 38632}",False,{'str': 244288},False
8,M4,object,3,281444,0.476588,"{'M0': 196405, 'M2': 59865, 'M1': 52826}",False,{'str': 309096},False
5,M1,object,2,271100,0.459071,"{'T': 319415, 'F': 25}",False,{'str': 319440},False
6,M2,object,2,271100,0.459071,"{'T': 285468, 'F': 33972}",False,{'str': 319440},False
7,M3,object,2,271100,0.459071,"{'T': 251731, 'F': 67709}",False,{'str': 319440},False
10,M6,object,2,169360,0.286788,"{'F': 227856, 'T': 193324}",False,{'str': 421180},False
3,P_emaildomain,object,59,94456,0.159949,"{'gmail.com': 228355, 'yahoo.com': 100934, 'ho...",False,{'str': 496084},False
1,card4,object,4,1577,0.002670,"{'visa': 384767, 'mastercard': 189217, 'americ...",False,{'str': 588963},False
2,card6,object,4,1571,0.002660,"{'debit': 439938, 'credit': 148986, 'debit or ...",False,{'str': 588969},False
0,ProductCD,object,5,0,0.000000,"{'W': 439670, 'C': 68519, 'R': 37699, 'H': 330...",False,{'str': 590540},False

In [8]:
print("High-cardinality categorical columns:")
display(categorical_audit[categorical_audit["high_cardinality"]].head(80))

print("Categorical columns with mixed Python value types:")
display(categorical_audit[categorical_audit["mixed_type_examples"]].head(80))

High-cardinality categorical columns:

Empty DataFrame
Columns: [column, dtype, unique_count, missing_count, missing_rate, top_values, high_cardinality, observed_python_types, mixed_type_examples]
Index: []

Categorical columns with mixed Python value types:

Empty DataFrame
Columns: [column, dtype, unique_count, missing_count, missing_rate, top_values, high_cardinality, observed_python_types, mixed_type_examples]
Index: []

## ID-Like Column Audit

ID-like columns often look numeric but behave as identifiers or categorical keys. This section recommends FeatureEngineeringV2 treatment.

In [9]:
def recommend_id_treatment(col: str, unique_count: int, missing_rate: float, dtype: str) -> str:
    if col == "TransactionID":
        return "ignored"
    if col.startswith("id_"):
        return "categorical" if unique_count < 1000 else "monitored"
    if col.startswith("card") or col.startswith("addr"):
        return "categorical"
    if missing_rate >= 0.9:
        return "monitored"
    return "monitored"


def audit_id_like_columns(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    rows = []
    n_rows = len(df)
    for col in columns:
        series = df[col]
        missing_count = int(series.isna().sum())
        unique_count = int(series.nunique(dropna=True))
        missing_rate = missing_count / n_rows if n_rows else np.nan
        rows.append({
            "column": col,
            "dtype": str(series.dtype),
            "unique_count": unique_count,
            "unique_rate": unique_count / n_rows if n_rows else np.nan,
            "missing_count": missing_count,
            "missing_rate": missing_rate,
            "behaves_like_unique_id": unique_count == n_rows,
            "recommended_treatment": recommend_id_treatment(col, unique_count, missing_rate, str(series.dtype)),
        })
    return pd.DataFrame(rows).sort_values(["recommended_treatment", "missing_rate", "unique_rate"], ascending=[True, False, False])


id_like_audit = audit_id_like_columns(merged, id_like_cols)
display(id_like_audit.head(120))

,column,dtype,unique_count,unique_rate,missing_count,missing_rate,behaves_like_unique_id,recommended_treatment
32,id_24,float64,12,0.000020,585793,0.991962,False,categorical
33,id_25,float64,341,0.000577,585408,0.991310,False,categorical
16,id_08,float64,94,0.000159,585385,0.991271,False,categorical
15,id_07,float64,84,0.000142,585385,0.991271,False,categorical
29,id_21,float64,490,0.000830,585381,0.991264,False,categorical
34,id_26,float64,95,0.000161,585377,0.991257,False,categorical
30,id_22,float64,25,0.000042,585371,0.991247,False,categorical
31,id_23,object,3,0.000005,585371,0.991247,False,categorical
35,id_27,object,2,0.000003,585371,0.991247,False,categorical
26,id_18,float64,18,0.000030,545427,0.923607,False,categorical
11,id_03,float64,24,0.000041,524216,0.887689,False,categorical
12,id_04,float64,15,0.000025,524216,0.887689,False,categorical
41,id_33,object,260,0.000440,517251,0.875895,False,categorical
18,id_10,float64,62,0.000105,515614,0.873123,False,categorical
17,id_09,float64,46,0.000078,515614,0.873123,False,categorical
38,id_30,object,75,0.000127,512975,0.868654,False,categorical
40,id_32,float64,4,0.000007,512954,0.868619,False,categorical
42,id_34,object,4,0.000007,512735,0.868248,False,categorical
22,id_14,float64,25,0.000042,510496,0.864456,False,categorical
21,id_13,float64,54,0.000091,463220,0.784401,False,categorical
24,id_16,object,2,0.000003,461200,0.780980,False,categorical
14,id_06,float64,101,0.000171,453675,0.768238,False,categorical
13,id_05,float64,93,0.000157,453675,0.768238,False,categorical
28,id_20,float64,394,0.000667,451279,0.764180,False,categorical
27,id_19,float64,522,0.000884,451222,0.764084,False,categorical
25,id_17,float64,104,0.000176,451171,0.763997,False,categorical
39,id_31,object,130,0.000220,450258,0.762451,False,categorical
19,id_11,float64,365,0.000618,449562,0.761273,False,categorical
36,id_28,object,2,0.000003,449562,0.761273,False,categorical
37,id_29,object,2,0.000003,449562,0.761273,False,categorical
23,id_15,object,3,0.000005,449555,0.761261,False,categorical
43,id_35,object,2,0.000003,449555,0.761261,False,categorical
44,id_36,object,2,0.000003,449555,0.761261,False,categorical
45,id_37,object,2,0.000003,449555,0.761261,False,categorical
46,id_38,object,2,0.000003,449555,0.761261,False,categorical
9,id_01,float64,77,0.000130,446307,0.755761,False,categorical
20,id_12,object,2,0.000003,446307,0.755761,False,categorical
7,addr1,float64,332,0.000562,65706,0.111264,False,categorical
8,addr2,float64,74,0.000125,65706,0.111264,False,categorical
2,card2,float64,500,0.000847,8933,0.015127,False,categorical
5,card5,float64,119,0.000202,4259,0.007212,False,categorical
4,card4,object,4,0.000007,1577,0.002670,False,categorical
6,card6,object,4,0.000007,1571,0.002660,False,categorical
3,card3,float64,114,0.000193,1565,0.002650,False,categorical
1,card1,int64,13553,0.022950,0,0.000000,False,categorical
0,TransactionID,int64,590540,1.000000,0,0.000000,True,ignored
10,id_02,float64,115655,0.195846,449668,0.761452,False,monitored

## Sample Risk Views

Small sampled views only, to keep the notebook lightweight.

In [10]:
sample_cols = [
    col for col in [
        "TransactionID", "TransactionDT", "isFraud", "TransactionAmt",
        "ProductCD", "card1", "card2", "card3", "card4", "card5", "card6",
        "addr1", "addr2", "P_emaildomain", "R_emaildomain", "DeviceType", "DeviceInfo",
    ] if col in merged.columns
]

display(merged[sample_cols].sample(min(20, len(merged)), random_state=42))

,TransactionID,TransactionDT,isFraud,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,P_emaildomain,R_emaildomain,DeviceType,DeviceInfo
470624,3457624,12153579,0,724.000,W,7826,481.0,150.0,mastercard,224.0,debit,387.0,87.0,aol.com,None,NaN,NaN
565820,3552820,15005886,0,108.500,W,12544,321.0,150.0,visa,226.0,debit,476.0,87.0,yahoo.com,None,NaN,NaN
284083,3271083,6970178,0,47.950,W,9400,111.0,150.0,mastercard,224.0,debit,315.0,87.0,gmail.com,None,NaN,NaN
239689,3226689,5673658,0,100.599,C,15885,545.0,185.0,visa,138.0,debit,NaN,NaN,gmail.com,gmail.com,NaN,NaN
281855,3268855,6886780,0,107.950,W,15497,490.0,150.0,visa,226.0,debit,299.0,87.0,hotmail.com,None,NaN,NaN
413908,3400908,10444930,0,280.000,W,7919,194.0,150.0,mastercard,166.0,debit,472.0,87.0,yahoo.com,None,NaN,NaN
413692,3400692,10442147,0,311.950,W,9002,453.0,150.0,visa,226.0,debit,315.0,87.0,yahoo.com,None,NaN,NaN
474182,3461182,12254683,0,330.990,W,14183,555.0,150.0,visa,226.0,credit,184.0,87.0,yahoo.com,None,NaN,NaN
370788,3357788,9228284,1,10.392,C,9633,130.0,185.0,visa,138.0,debit,NaN,NaN,icloud.com,icloud.com,desktop,Windows
28757,3015757,739585,0,335.000,W,11207,361.0,150.0,visa,226.0,debit,231.0,87.0,hotmail.com,None,NaN,NaN
376486,3363486,9409651,0,57.000,W,9500,321.0,150.0,visa,226.0,debit,204.0,87.0,gmail.com,None,NaN,NaN
75586,3062586,1649422,0,108.950,W,17188,321.0,150.0,visa,226.0,debit,299.0,87.0,yahoo.com,None,NaN,NaN
162190,3149190,3436459,0,222.000,W,15066,170.0,150.0,mastercard,102.0,credit,325.0,87.0,None,None,NaN,NaN
460768,3447768,11835503,0,209.950,W,1804,161.0,150.0,mastercard,117.0,debit,123.0,87.0,anonymous.com,None,NaN,NaN
274179,3261179,6650153,0,270.000,W,18249,360.0,150.0,mastercard,126.0,debit,205.0,87.0,gmail.com,None,NaN,NaN
88699,3075699,1873107,0,100.000,R,17188,321.0,150.0,visa,226.0,debit,299.0,87.0,gmail.com,yahoo.com,mobile,iOS Device
203551,3190551,4656646,0,107.950,W,7919,194.0,150.0,mastercard,202.0,debit,264.0,87.0,None,None,NaN,NaN
207863,3194863,4801943,0,439.990,W,6341,555.0,150.0,mastercard,195.0,credit,203.0,87.0,yahoo.com,None,NaN,NaN
561187,3548187,14860149,0,47.950,W,7638,174.0,150.0,visa,166.0,debit,315.0,87.0,gmail.com,None,NaN,NaN
538434,3525434,14186414,0,58.950,W,16132,111.0,150.0,visa,226.0,debit,299.0,87.0,gmail.com,None,NaN,NaN

## Final Summary

### Key Data Quality Risks

- Many IEEE fraud columns are sparse, especially identity/device fields after the left merge. FeatureEngineeringV2 should treat missingness as signal where appropriate.
- Card, address, and `id_*` columns may be numeric dtype but often behave like categorical identifiers rather than continuous measurements.
- High-cardinality categorical fields such as device, email, card, and identity features can create instability if encoded naively.
- Near-constant or extremely sparse columns may add noise, latency, or brittle schema behavior.
- Large ranges and outliers in amount or count-like fields should be reviewed before adding transformations or clipping.

### Recommended FeatureEngineeringV2 Validation Improvements

- Add explicit dtype policy by column group: continuous numeric, categorical identifier, ignored ID, and monitored-only fields.
- Add missing-value indicators for sparse numeric fields where missingness is predictive.
- Use `__MISSING__` and `__UNKNOWN__` handling for categorical features and high-cardinality identifiers.
- Treat `TransactionID` as an ignored join/audit key, not a model feature.
- Treat `card*`, `addr*`, and selected `id_*` fields as categorical/frequency-encoded unless there is evidence they are true measurements.
- Add checks that future-looking fields such as `uid_time_to_next` are excluded from v2.

### Recommended Monitoring Checks

- Track missing-rate drift by column group.
- Track unseen-category rates for categorical and ID-like fields.
- Track feature range and outlier drift for numerical fields.
- Track cardinality changes for card, address, email, device, and identity columns.
- Track constant or near-constant features after transformation.

### Scope Note

This notebook is exploratory only. No production code changes, model training, v1 artifact changes, `/predict` changes, or model artifact writes are performed here. Code changes should be made later only if explicitly requested.